version: '1.0'
services:
  web:
    build:
      context: .
    command: gunicorn -b 0.0.0.0:8000 app:app
    ports:
      - "8000:8000"
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"
    environment:
      - FLASK_ENV=production
